title: Vecmath gem for Visor etc.
email: mamba2928@yahoo.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Her we describe how to use some cool JRubyArt features in Visor
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ruby-processing.github.io/vecmath" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: monkstoneT
github_username:  monkstone
future: true
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
syntax-highlighting:
  enabled: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
